package com.contextcondenser.services

import com.intellij.openapi.application.ReadAction
import com.intellij.openapi.components.Service
import com.intellij.openapi.components.service
import com.intellij.openapi.diagnostic.thisLogger
import com.intellij.openapi.fileEditor.FileDocumentManager
import com.intellij.openapi.progress.ProgressIndicator
import com.intellij.openapi.project.Project
import com.intellij.openapi.project.guessProjectDir
import com.intellij.openapi.roots.ProjectRootManager
import com.intellij.openapi.vfs.VfsUtil
import com.intellij.openapi.vfs.VirtualFile

@Service(Service.Level.PROJECT)
class ProjectSkeletonService(private val project: Project) {

    private val log = thisLogger()
    private val settings get() = CondenserSettings.getInstance().state
    private val excludePatterns: List<String> by lazy {
        settings.excludePatterns.split(",").map { it.trim() }.filter { it.isNotBlank() }
    }

    data class ProjectSkeletonResult(
        val markdown: String,
        val totalRawTokens: Int,
        val totalCondensedTokens: Int,
        val filesProcessed: Int,
        val filesTruncated: Int,
    ) {
        val savingsPercent: Int
            get() = if (totalRawTokens > 0) 100 - (totalCondensedTokens * 100 / totalRawTokens) else 0
    }

    fun generateProjectSkeleton(indicator: ProgressIndicator? = null): ProjectSkeletonResult {
        val manager = project.service<CondenserManager>()
        val builder = StringBuilder()
        var totalRaw = 0
        var totalCondensed = 0
        var processed = 0
        var truncated = 0

        builder.appendLine("# Project Skeleton: ${project.name}")
        builder.appendLine()
        builder.appendLine("> Generated by Context Condenser — LVM")
        builder.appendLine("> Implementation bodies condensed with `...` to reduce token cost.")
        builder.appendLine()

        val pythonFiles = collectPythonFiles()

        for ((index, file) in pythonFiles.withIndex()) {
            if (totalCondensed >= settings.maxProjectTokens) {
                truncated = pythonFiles.size - index
                builder.appendLine(
                    "---\n> Token budget reached. $truncated file(s) omitted. " +
                    "Increase `maxProjectTokens` in settings or use per-file mode."
                )
                break
            }

            indicator?.apply {
                fraction = index.toDouble() / pythonFiles.size
                text = "Condensing ${file.name}..."
            }

            // FIX: FileDocumentManager.getDocument() requires a read-action on background threads
            val raw = ReadAction.compute<String?, Throwable> {
                FileDocumentManager.getInstance().getDocument(file)?.text
            } ?: continue

            if (raw.isBlank()) continue

            val result = manager.condenseContent(raw)
            totalRaw += result.rawTokens
            totalCondensed += result.condensedTokens
            processed++

            val relativePath = file.path.removePrefix(project.basePath ?: "").trimStart('/')

            builder.appendLine("## `$relativePath`")
            builder.appendLine()
            if (result.error != null) {
                builder.appendLine("> Error: ${result.error}")
            } else {
                builder.appendLine("```python")
                builder.appendLine(result.content)
                builder.appendLine("```")
            }
            builder.appendLine()
            builder.appendLine(
                "_${result.rawTokens} raw → ${result.condensedTokens} condensed " +
                "(${result.savingsPercent}% saved)_"
            )
            builder.appendLine()
        }

        val overallSavings = if (totalRaw > 0) 100 - (totalCondensed * 100 / totalRaw) else 0
        builder.appendLine("---")
        builder.appendLine("## Summary")
        builder.appendLine()
        builder.appendLine("| Metric | Value |")
        builder.appendLine("|---|---|")
        builder.appendLine("| Files processed | $processed |")
        builder.appendLine("| Raw tokens | ${"%,d".format(totalRaw)} |")
        builder.appendLine("| Condensed tokens | ${"%,d".format(totalCondensed)} |")
        builder.appendLine("| Overall savings | $overallSavings% |")
        if (truncated > 0) builder.appendLine("| Files omitted (budget) | $truncated |")

        return ProjectSkeletonResult(
            markdown = builder.toString(),
            totalRawTokens = totalRaw,
            totalCondensedTokens = totalCondensed,
            filesProcessed = processed,
            filesTruncated = truncated,
        )
    }

    private fun collectPythonFiles(): List<VirtualFile> {
        val files = mutableListOf<VirtualFile>()

        // Always include project base dir; add configured source roots on top
        val sourceRoots = ProjectRootManager.getInstance(project).contentSourceRoots.toList()
        val baseDir = project.guessProjectDir()
        val roots = (listOfNotNull(baseDir) + sourceRoots).distinctBy { it.path }

        roots.forEach { root ->
            VfsUtil.iterateChildrenRecursively(root, null) { file ->
                if (!file.isDirectory && file.extension == "py" && !isExcluded(file)) {
                    files.add(file)
                }
                true
            }
        }
        return files.sortedBy { it.path }
    }

    private fun isExcluded(file: VirtualFile): Boolean =
        excludePatterns.any { pattern -> file.path.contains(pattern) }
}
